// Minimal Starlink dish proto — field numbers from live gRPC reflection.
// Verify live: grpcurl -plaintext 192.168.100.1:9200 describe SpaceX.API.Device.DishGetStatusResponse
// Regenerate stubs: make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/device.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateLimitReason int32

const (
	RateLimitReason_RATE_LIMIT_UNKNOWN          RateLimitReason = 0
	RateLimitReason_RATE_LIMIT_NONE             RateLimitReason = 1
	RateLimitReason_RATE_LIMIT_POLICY           RateLimitReason = 2
	RateLimitReason_RATE_LIMIT_USER_CUSTOM      RateLimitReason = 3
	RateLimitReason_RATE_LIMIT_OVERAGE          RateLimitReason = 5
	RateLimitReason_RATE_LIMIT_LOW_SPEED_POLICY RateLimitReason = 6
)

// Enum value maps for RateLimitReason.
var (
	RateLimitReason_name = map[int32]string{
		0: "RATE_LIMIT_UNKNOWN",
		1: "RATE_LIMIT_NONE",
		2: "RATE_LIMIT_POLICY",
		3: "RATE_LIMIT_USER_CUSTOM",
		5: "RATE_LIMIT_OVERAGE",
		6: "RATE_LIMIT_LOW_SPEED_POLICY",
	}
	RateLimitReason_value = map[string]int32{
		"RATE_LIMIT_UNKNOWN":          0,
		"RATE_LIMIT_NONE":             1,
		"RATE_LIMIT_POLICY":           2,
		"RATE_LIMIT_USER_CUSTOM":      3,
		"RATE_LIMIT_OVERAGE":          5,
		"RATE_LIMIT_LOW_SPEED_POLICY": 6,
	}
)

func (x RateLimitReason) Enum() *RateLimitReason {
	p := new(RateLimitReason)
	*p = x
	return p
}

func (x RateLimitReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateLimitReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_device_proto_enumTypes[0].Descriptor()
}

func (RateLimitReason) Type() protoreflect.EnumType {
	return &file_proto_device_proto_enumTypes[0]
}

func (x RateLimitReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateLimitReason.Descriptor instead.
func (RateLimitReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{0}
}

type DishOutage_Cause int32

const (
	DishOutage_UNKNOWN           DishOutage_Cause = 0
	DishOutage_BOOTING           DishOutage_Cause = 1
	DishOutage_STOWED            DishOutage_Cause = 2
	DishOutage_THERMAL_SHUTDOWN  DishOutage_Cause = 3
	DishOutage_NO_SCHEDULE       DishOutage_Cause = 4
	DishOutage_NO_SATS           DishOutage_Cause = 5
	DishOutage_OBSTRUCTED        DishOutage_Cause = 6
	DishOutage_NO_DOWNLINK       DishOutage_Cause = 7
	DishOutage_NO_PINGS          DishOutage_Cause = 8
	DishOutage_ACTUATOR_ACTIVITY DishOutage_Cause = 9
	DishOutage_CABLE_TEST        DishOutage_Cause = 10
	DishOutage_SLEEPING          DishOutage_Cause = 11
	DishOutage_SKY_SEARCH        DishOutage_Cause = 13
	DishOutage_INHIBIT_RF        DishOutage_Cause = 14
)

// Enum value maps for DishOutage_Cause.
var (
	DishOutage_Cause_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "BOOTING",
		2:  "STOWED",
		3:  "THERMAL_SHUTDOWN",
		4:  "NO_SCHEDULE",
		5:  "NO_SATS",
		6:  "OBSTRUCTED",
		7:  "NO_DOWNLINK",
		8:  "NO_PINGS",
		9:  "ACTUATOR_ACTIVITY",
		10: "CABLE_TEST",
		11: "SLEEPING",
		13: "SKY_SEARCH",
		14: "INHIBIT_RF",
	}
	DishOutage_Cause_value = map[string]int32{
		"UNKNOWN":           0,
		"BOOTING":           1,
		"STOWED":            2,
		"THERMAL_SHUTDOWN":  3,
		"NO_SCHEDULE":       4,
		"NO_SATS":           5,
		"OBSTRUCTED":        6,
		"NO_DOWNLINK":       7,
		"NO_PINGS":          8,
		"ACTUATOR_ACTIVITY": 9,
		"CABLE_TEST":        10,
		"SLEEPING":          11,
		"SKY_SEARCH":        13,
		"INHIBIT_RF":        14,
	}
)

func (x DishOutage_Cause) Enum() *DishOutage_Cause {
	p := new(DishOutage_Cause)
	*p = x
	return p
}

func (x DishOutage_Cause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DishOutage_Cause) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_device_proto_enumTypes[1].Descriptor()
}

func (DishOutage_Cause) Type() protoreflect.EnumType {
	return &file_proto_device_proto_enumTypes[1]
}

func (x DishOutage_Cause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DishOutage_Cause.Descriptor instead.
func (DishOutage_Cause) EnumDescriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{11, 0}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*Request_GetStatus
	//	*Request_GetHistory
	//	*Request_GetDeviceInfo
	Request       isRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRequest() isRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Request) GetGetStatus() *GetStatusRequest {
	if x != nil {
		if x, ok := x.Request.(*Request_GetStatus); ok {
			return x.GetStatus
		}
	}
	return nil
}

func (x *Request) GetGetHistory() *GetHistoryRequest {
	if x != nil {
		if x, ok := x.Request.(*Request_GetHistory); ok {
			return x.GetHistory
		}
	}
	return nil
}

func (x *Request) GetGetDeviceInfo() *GetDeviceInfoRequest {
	if x != nil {
		if x, ok := x.Request.(*Request_GetDeviceInfo); ok {
			return x.GetDeviceInfo
		}
	}
	return nil
}

type isRequest_Request interface {
	isRequest_Request()
}

type Request_GetStatus struct {
	GetStatus *GetStatusRequest `protobuf:"bytes,1004,opt,name=get_status,json=getStatus,proto3,oneof"`
}

type Request_GetHistory struct {
	GetHistory *GetHistoryRequest `protobuf:"bytes,1007,opt,name=get_history,json=getHistory,proto3,oneof"`
}

type Request_GetDeviceInfo struct {
	GetDeviceInfo *GetDeviceInfoRequest `protobuf:"bytes,1008,opt,name=get_device_info,json=getDeviceInfo,proto3,oneof"`
}

func (*Request_GetStatus) isRequest_Request() {}

func (*Request_GetHistory) isRequest_Request() {}

func (*Request_GetDeviceInfo) isRequest_Request() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*Response_DishGetStatus
	//	*Response_DishGetHistory
	//	*Response_GetDeviceInfo
	Response      isResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResponse() isResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Response) GetDishGetStatus() *DishGetStatusResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_DishGetStatus); ok {
			return x.DishGetStatus
		}
	}
	return nil
}

func (x *Response) GetDishGetHistory() *DishGetHistoryResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_DishGetHistory); ok {
			return x.DishGetHistory
		}
	}
	return nil
}

func (x *Response) GetGetDeviceInfo() *GetDeviceInfoResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_GetDeviceInfo); ok {
			return x.GetDeviceInfo
		}
	}
	return nil
}

type isResponse_Response interface {
	isResponse_Response()
}

type Response_DishGetStatus struct {
	DishGetStatus *DishGetStatusResponse `protobuf:"bytes,2004,opt,name=dish_get_status,json=dishGetStatus,proto3,oneof"`
}

type Response_DishGetHistory struct {
	DishGetHistory *DishGetHistoryResponse `protobuf:"bytes,2006,opt,name=dish_get_history,json=dishGetHistory,proto3,oneof"`
}

type Response_GetDeviceInfo struct {
	GetDeviceInfo *GetDeviceInfoResponse `protobuf:"bytes,1004,opt,name=get_device_info,json=getDeviceInfo,proto3,oneof"`
}

func (*Response_DishGetStatus) isResponse_Response() {}

func (*Response_DishGetHistory) isResponse_Response() {}

func (*Response_GetDeviceInfo) isResponse_Response() {}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{2}
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{3}
}

type GetDeviceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceInfoRequest) Reset() {
	*x = GetDeviceInfoRequest{}
	mi := &file_proto_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceInfoRequest) ProtoMessage() {}

func (x *GetDeviceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{4}
}

type GetDeviceInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo    *DeviceInfo            `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceInfoResponse) Reset() {
	*x = GetDeviceInfoResponse{}
	mi := &file_proto_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceInfoResponse) ProtoMessage() {}

func (x *GetDeviceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeviceInfoResponse) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type DeviceInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HardwareVersion string                 `protobuf:"bytes,2,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,3,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	CountryCode     string                 `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	UtcOffsetS      int32                  `protobuf:"varint,5,opt,name=utc_offset_s,json=utcOffsetS,proto3" json:"utc_offset_s,omitempty"`
	Bootcount       int32                  `protobuf:"varint,8,opt,name=bootcount,proto3" json:"bootcount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *DeviceInfo) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *DeviceInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *DeviceInfo) GetUtcOffsetS() int32 {
	if x != nil {
		return x.UtcOffsetS
	}
	return 0
}

func (x *DeviceInfo) GetBootcount() int32 {
	if x != nil {
		return x.Bootcount
	}
	return 0
}

type DishGetStatusResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo                  *DeviceInfo            `protobuf:"bytes,1,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	DeviceState                 *DeviceState           `protobuf:"bytes,2,opt,name=device_state,json=deviceState,proto3" json:"device_state,omitempty"`
	PopPingDropRate             float32                `protobuf:"fixed32,1003,opt,name=pop_ping_drop_rate,json=popPingDropRate,proto3" json:"pop_ping_drop_rate,omitempty"`
	ObstructionStats            *DishObstructionStats  `protobuf:"bytes,1004,opt,name=obstruction_stats,json=obstructionStats,proto3" json:"obstruction_stats,omitempty"`
	Alerts                      *DishAlerts            `protobuf:"bytes,1005,opt,name=alerts,proto3" json:"alerts,omitempty"`
	DownlinkThroughputBps       float32                `protobuf:"fixed32,1007,opt,name=downlink_throughput_bps,json=downlinkThroughputBps,proto3" json:"downlink_throughput_bps,omitempty"`
	UplinkThroughputBps         float32                `protobuf:"fixed32,1008,opt,name=uplink_throughput_bps,json=uplinkThroughputBps,proto3" json:"uplink_throughput_bps,omitempty"`
	PopPingLatencyMs            float32                `protobuf:"fixed32,1009,opt,name=pop_ping_latency_ms,json=popPingLatencyMs,proto3" json:"pop_ping_latency_ms,omitempty"`
	BoresightAzimuthDeg         float32                `protobuf:"fixed32,1011,opt,name=boresight_azimuth_deg,json=boresightAzimuthDeg,proto3" json:"boresight_azimuth_deg,omitempty"`
	BoresightElevationDeg       float32                `protobuf:"fixed32,1012,opt,name=boresight_elevation_deg,json=boresightElevationDeg,proto3" json:"boresight_elevation_deg,omitempty"`
	Outage                      *DishOutage            `protobuf:"bytes,1014,opt,name=outage,proto3" json:"outage,omitempty"`
	EthSpeedMbps                int32                  `protobuf:"varint,1016,opt,name=eth_speed_mbps,json=ethSpeedMbps,proto3" json:"eth_speed_mbps,omitempty"`
	IsSnrAboveNoiseFloor        bool                   `protobuf:"varint,1018,opt,name=is_snr_above_noise_floor,json=isSnrAboveNoiseFloor,proto3" json:"is_snr_above_noise_floor,omitempty"`
	IsSnrPersistentlyLow        bool                   `protobuf:"varint,1022,opt,name=is_snr_persistently_low,json=isSnrPersistentlyLow,proto3" json:"is_snr_persistently_low,omitempty"`
	AlignmentStats              *AlignmentStats        `protobuf:"bytes,1027,opt,name=alignment_stats,json=alignmentStats,proto3" json:"alignment_stats,omitempty"`
	IsCellDisabled              bool                   `protobuf:"varint,1029,opt,name=is_cell_disabled,json=isCellDisabled,proto3" json:"is_cell_disabled,omitempty"`
	DlBandwidthRestrictedReason RateLimitReason        `protobuf:"varint,1044,opt,name=dl_bandwidth_restricted_reason,json=dlBandwidthRestrictedReason,proto3,enum=SpaceX.API.Device.RateLimitReason" json:"dl_bandwidth_restricted_reason,omitempty"`
	UlBandwidthRestrictedReason RateLimitReason        `protobuf:"varint,1045,opt,name=ul_bandwidth_restricted_reason,json=ulBandwidthRestrictedReason,proto3,enum=SpaceX.API.Device.RateLimitReason" json:"ul_bandwidth_restricted_reason,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DishGetStatusResponse) Reset() {
	*x = DishGetStatusResponse{}
	mi := &file_proto_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishGetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishGetStatusResponse) ProtoMessage() {}

func (x *DishGetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishGetStatusResponse.ProtoReflect.Descriptor instead.
func (*DishGetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{7}
}

func (x *DishGetStatusResponse) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *DishGetStatusResponse) GetDeviceState() *DeviceState {
	if x != nil {
		return x.DeviceState
	}
	return nil
}

func (x *DishGetStatusResponse) GetPopPingDropRate() float32 {
	if x != nil {
		return x.PopPingDropRate
	}
	return 0
}

func (x *DishGetStatusResponse) GetObstructionStats() *DishObstructionStats {
	if x != nil {
		return x.ObstructionStats
	}
	return nil
}

func (x *DishGetStatusResponse) GetAlerts() *DishAlerts {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *DishGetStatusResponse) GetDownlinkThroughputBps() float32 {
	if x != nil {
		return x.DownlinkThroughputBps
	}
	return 0
}

func (x *DishGetStatusResponse) GetUplinkThroughputBps() float32 {
	if x != nil {
		return x.UplinkThroughputBps
	}
	return 0
}

func (x *DishGetStatusResponse) GetPopPingLatencyMs() float32 {
	if x != nil {
		return x.PopPingLatencyMs
	}
	return 0
}

func (x *DishGetStatusResponse) GetBoresightAzimuthDeg() float32 {
	if x != nil {
		return x.BoresightAzimuthDeg
	}
	return 0
}

func (x *DishGetStatusResponse) GetBoresightElevationDeg() float32 {
	if x != nil {
		return x.BoresightElevationDeg
	}
	return 0
}

func (x *DishGetStatusResponse) GetOutage() *DishOutage {
	if x != nil {
		return x.Outage
	}
	return nil
}

func (x *DishGetStatusResponse) GetEthSpeedMbps() int32 {
	if x != nil {
		return x.EthSpeedMbps
	}
	return 0
}

func (x *DishGetStatusResponse) GetIsSnrAboveNoiseFloor() bool {
	if x != nil {
		return x.IsSnrAboveNoiseFloor
	}
	return false
}

func (x *DishGetStatusResponse) GetIsSnrPersistentlyLow() bool {
	if x != nil {
		return x.IsSnrPersistentlyLow
	}
	return false
}

func (x *DishGetStatusResponse) GetAlignmentStats() *AlignmentStats {
	if x != nil {
		return x.AlignmentStats
	}
	return nil
}

func (x *DishGetStatusResponse) GetIsCellDisabled() bool {
	if x != nil {
		return x.IsCellDisabled
	}
	return false
}

func (x *DishGetStatusResponse) GetDlBandwidthRestrictedReason() RateLimitReason {
	if x != nil {
		return x.DlBandwidthRestrictedReason
	}
	return RateLimitReason_RATE_LIMIT_UNKNOWN
}

func (x *DishGetStatusResponse) GetUlBandwidthRestrictedReason() RateLimitReason {
	if x != nil {
		return x.UlBandwidthRestrictedReason
	}
	return RateLimitReason_RATE_LIMIT_UNKNOWN
}

type DeviceState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UptimeS       uint64                 `protobuf:"varint,1,opt,name=uptime_s,json=uptimeS,proto3" json:"uptime_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceState) Reset() {
	*x = DeviceState{}
	mi := &file_proto_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceState) ProtoMessage() {}

func (x *DeviceState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceState.ProtoReflect.Descriptor instead.
func (*DeviceState) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceState) GetUptimeS() uint64 {
	if x != nil {
		return x.UptimeS
	}
	return 0
}

type DishObstructionStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FractionObstructed  float32                `protobuf:"fixed32,1,opt,name=fraction_obstructed,json=fractionObstructed,proto3" json:"fraction_obstructed,omitempty"`
	ValidS              float32                `protobuf:"fixed32,4,opt,name=valid_s,json=validS,proto3" json:"valid_s,omitempty"`
	CurrentlyObstructed bool                   `protobuf:"varint,5,opt,name=currently_obstructed,json=currentlyObstructed,proto3" json:"currently_obstructed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DishObstructionStats) Reset() {
	*x = DishObstructionStats{}
	mi := &file_proto_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishObstructionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishObstructionStats) ProtoMessage() {}

func (x *DishObstructionStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishObstructionStats.ProtoReflect.Descriptor instead.
func (*DishObstructionStats) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{9}
}

func (x *DishObstructionStats) GetFractionObstructed() float32 {
	if x != nil {
		return x.FractionObstructed
	}
	return 0
}

func (x *DishObstructionStats) GetValidS() float32 {
	if x != nil {
		return x.ValidS
	}
	return 0
}

func (x *DishObstructionStats) GetCurrentlyObstructed() bool {
	if x != nil {
		return x.CurrentlyObstructed
	}
	return false
}

type DishAlerts struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	MotorsStuck                bool                   `protobuf:"varint,1,opt,name=motors_stuck,json=motorsStuck,proto3" json:"motors_stuck,omitempty"`
	ThermalShutdown            bool                   `protobuf:"varint,2,opt,name=thermal_shutdown,json=thermalShutdown,proto3" json:"thermal_shutdown,omitempty"`
	ThermalThrottle            bool                   `protobuf:"varint,3,opt,name=thermal_throttle,json=thermalThrottle,proto3" json:"thermal_throttle,omitempty"`
	UnexpectedLocation         bool                   `protobuf:"varint,4,opt,name=unexpected_location,json=unexpectedLocation,proto3" json:"unexpected_location,omitempty"`
	MastNotNearVertical        bool                   `protobuf:"varint,5,opt,name=mast_not_near_vertical,json=mastNotNearVertical,proto3" json:"mast_not_near_vertical,omitempty"`
	SlowEthernetSpeeds         bool                   `protobuf:"varint,6,opt,name=slow_ethernet_speeds,json=slowEthernetSpeeds,proto3" json:"slow_ethernet_speeds,omitempty"`
	Roaming                    bool                   `protobuf:"varint,7,opt,name=roaming,proto3" json:"roaming,omitempty"`
	InstallPending             bool                   `protobuf:"varint,8,opt,name=install_pending,json=installPending,proto3" json:"install_pending,omitempty"`
	IsHeating                  bool                   `protobuf:"varint,9,opt,name=is_heating,json=isHeating,proto3" json:"is_heating,omitempty"`
	PowerSupplyThermalThrottle bool                   `protobuf:"varint,10,opt,name=power_supply_thermal_throttle,json=powerSupplyThermalThrottle,proto3" json:"power_supply_thermal_throttle,omitempty"`
	IsPowerSaveIdle            bool                   `protobuf:"varint,11,opt,name=is_power_save_idle,json=isPowerSaveIdle,proto3" json:"is_power_save_idle,omitempty"`
	DbfTelemStale              bool                   `protobuf:"varint,14,opt,name=dbf_telem_stale,json=dbfTelemStale,proto3" json:"dbf_telem_stale,omitempty"`
	LowMotorCurrent            bool                   `protobuf:"varint,16,opt,name=low_motor_current,json=lowMotorCurrent,proto3" json:"low_motor_current,omitempty"`
	LowerSignalThanPredicted   bool                   `protobuf:"varint,17,opt,name=lower_signal_than_predicted,json=lowerSignalThanPredicted,proto3" json:"lower_signal_than_predicted,omitempty"`
	SlowEthernetSpeeds_100     bool                   `protobuf:"varint,18,opt,name=slow_ethernet_speeds_100,json=slowEthernetSpeeds100,proto3" json:"slow_ethernet_speeds_100,omitempty"`
	ObstructionMapReset        bool                   `protobuf:"varint,19,opt,name=obstruction_map_reset,json=obstructionMapReset,proto3" json:"obstruction_map_reset,omitempty"`
	DishWaterDetected          bool                   `protobuf:"varint,20,opt,name=dish_water_detected,json=dishWaterDetected,proto3" json:"dish_water_detected,omitempty"`
	RouterWaterDetected        bool                   `protobuf:"varint,21,opt,name=router_water_detected,json=routerWaterDetected,proto3" json:"router_water_detected,omitempty"`
	UpsuRouterPortSlow         bool                   `protobuf:"varint,22,opt,name=upsu_router_port_slow,json=upsuRouterPortSlow,proto3" json:"upsu_router_port_slow,omitempty"`
	NoEthernetLink             bool                   `protobuf:"varint,23,opt,name=no_ethernet_link,json=noEthernetLink,proto3" json:"no_ethernet_link,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DishAlerts) Reset() {
	*x = DishAlerts{}
	mi := &file_proto_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishAlerts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishAlerts) ProtoMessage() {}

func (x *DishAlerts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishAlerts.ProtoReflect.Descriptor instead.
func (*DishAlerts) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{10}
}

func (x *DishAlerts) GetMotorsStuck() bool {
	if x != nil {
		return x.MotorsStuck
	}
	return false
}

func (x *DishAlerts) GetThermalShutdown() bool {
	if x != nil {
		return x.ThermalShutdown
	}
	return false
}

func (x *DishAlerts) GetThermalThrottle() bool {
	if x != nil {
		return x.ThermalThrottle
	}
	return false
}

func (x *DishAlerts) GetUnexpectedLocation() bool {
	if x != nil {
		return x.UnexpectedLocation
	}
	return false
}

func (x *DishAlerts) GetMastNotNearVertical() bool {
	if x != nil {
		return x.MastNotNearVertical
	}
	return false
}

func (x *DishAlerts) GetSlowEthernetSpeeds() bool {
	if x != nil {
		return x.SlowEthernetSpeeds
	}
	return false
}

func (x *DishAlerts) GetRoaming() bool {
	if x != nil {
		return x.Roaming
	}
	return false
}

func (x *DishAlerts) GetInstallPending() bool {
	if x != nil {
		return x.InstallPending
	}
	return false
}

func (x *DishAlerts) GetIsHeating() bool {
	if x != nil {
		return x.IsHeating
	}
	return false
}

func (x *DishAlerts) GetPowerSupplyThermalThrottle() bool {
	if x != nil {
		return x.PowerSupplyThermalThrottle
	}
	return false
}

func (x *DishAlerts) GetIsPowerSaveIdle() bool {
	if x != nil {
		return x.IsPowerSaveIdle
	}
	return false
}

func (x *DishAlerts) GetDbfTelemStale() bool {
	if x != nil {
		return x.DbfTelemStale
	}
	return false
}

func (x *DishAlerts) GetLowMotorCurrent() bool {
	if x != nil {
		return x.LowMotorCurrent
	}
	return false
}

func (x *DishAlerts) GetLowerSignalThanPredicted() bool {
	if x != nil {
		return x.LowerSignalThanPredicted
	}
	return false
}

func (x *DishAlerts) GetSlowEthernetSpeeds_100() bool {
	if x != nil {
		return x.SlowEthernetSpeeds_100
	}
	return false
}

func (x *DishAlerts) GetObstructionMapReset() bool {
	if x != nil {
		return x.ObstructionMapReset
	}
	return false
}

func (x *DishAlerts) GetDishWaterDetected() bool {
	if x != nil {
		return x.DishWaterDetected
	}
	return false
}

func (x *DishAlerts) GetRouterWaterDetected() bool {
	if x != nil {
		return x.RouterWaterDetected
	}
	return false
}

func (x *DishAlerts) GetUpsuRouterPortSlow() bool {
	if x != nil {
		return x.UpsuRouterPortSlow
	}
	return false
}

func (x *DishAlerts) GetNoEthernetLink() bool {
	if x != nil {
		return x.NoEthernetLink
	}
	return false
}

type DishOutage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Cause            DishOutage_Cause       `protobuf:"varint,1,opt,name=cause,proto3,enum=SpaceX.API.Device.DishOutage_Cause" json:"cause,omitempty"`
	StartTimestampNs int64                  `protobuf:"varint,2,opt,name=start_timestamp_ns,json=startTimestampNs,proto3" json:"start_timestamp_ns,omitempty"`
	DurationNs       uint64                 `protobuf:"varint,3,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	DidSwitch        bool                   `protobuf:"varint,4,opt,name=did_switch,json=didSwitch,proto3" json:"did_switch,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DishOutage) Reset() {
	*x = DishOutage{}
	mi := &file_proto_device_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishOutage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishOutage) ProtoMessage() {}

func (x *DishOutage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishOutage.ProtoReflect.Descriptor instead.
func (*DishOutage) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{11}
}

func (x *DishOutage) GetCause() DishOutage_Cause {
	if x != nil {
		return x.Cause
	}
	return DishOutage_UNKNOWN
}

func (x *DishOutage) GetStartTimestampNs() int64 {
	if x != nil {
		return x.StartTimestampNs
	}
	return 0
}

func (x *DishOutage) GetDurationNs() uint64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

func (x *DishOutage) GetDidSwitch() bool {
	if x != nil {
		return x.DidSwitch
	}
	return false
}

type AlignmentStats struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	TiltAngleDeg                 float32                `protobuf:"fixed32,3,opt,name=tilt_angle_deg,json=tiltAngleDeg,proto3" json:"tilt_angle_deg,omitempty"`
	BoresightAzimuthDeg          float32                `protobuf:"fixed32,4,opt,name=boresight_azimuth_deg,json=boresightAzimuthDeg,proto3" json:"boresight_azimuth_deg,omitempty"`
	BoresightElevationDeg        float32                `protobuf:"fixed32,5,opt,name=boresight_elevation_deg,json=boresightElevationDeg,proto3" json:"boresight_elevation_deg,omitempty"`
	AttitudeUncertaintyDeg       float32                `protobuf:"fixed32,7,opt,name=attitude_uncertainty_deg,json=attitudeUncertaintyDeg,proto3" json:"attitude_uncertainty_deg,omitempty"`
	DesiredBoresightAzimuthDeg   float32                `protobuf:"fixed32,8,opt,name=desired_boresight_azimuth_deg,json=desiredBoresightAzimuthDeg,proto3" json:"desired_boresight_azimuth_deg,omitempty"`
	DesiredBoresightElevationDeg float32                `protobuf:"fixed32,9,opt,name=desired_boresight_elevation_deg,json=desiredBoresightElevationDeg,proto3" json:"desired_boresight_elevation_deg,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *AlignmentStats) Reset() {
	*x = AlignmentStats{}
	mi := &file_proto_device_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignmentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignmentStats) ProtoMessage() {}

func (x *AlignmentStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignmentStats.ProtoReflect.Descriptor instead.
func (*AlignmentStats) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{12}
}

func (x *AlignmentStats) GetTiltAngleDeg() float32 {
	if x != nil {
		return x.TiltAngleDeg
	}
	return 0
}

func (x *AlignmentStats) GetBoresightAzimuthDeg() float32 {
	if x != nil {
		return x.BoresightAzimuthDeg
	}
	return 0
}

func (x *AlignmentStats) GetBoresightElevationDeg() float32 {
	if x != nil {
		return x.BoresightElevationDeg
	}
	return 0
}

func (x *AlignmentStats) GetAttitudeUncertaintyDeg() float32 {
	if x != nil {
		return x.AttitudeUncertaintyDeg
	}
	return 0
}

func (x *AlignmentStats) GetDesiredBoresightAzimuthDeg() float32 {
	if x != nil {
		return x.DesiredBoresightAzimuthDeg
	}
	return 0
}

func (x *AlignmentStats) GetDesiredBoresightElevationDeg() float32 {
	if x != nil {
		return x.DesiredBoresightElevationDeg
	}
	return 0
}

type DishGetHistoryResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Current               uint64                 `protobuf:"varint,1,opt,name=current,proto3" json:"current,omitempty"`
	PopPingDropRate       []float32              `protobuf:"fixed32,1001,rep,packed,name=pop_ping_drop_rate,json=popPingDropRate,proto3" json:"pop_ping_drop_rate,omitempty"`
	PopPingLatencyMs      []float32              `protobuf:"fixed32,1002,rep,packed,name=pop_ping_latency_ms,json=popPingLatencyMs,proto3" json:"pop_ping_latency_ms,omitempty"`
	DownlinkThroughputBps []float32              `protobuf:"fixed32,1003,rep,packed,name=downlink_throughput_bps,json=downlinkThroughputBps,proto3" json:"downlink_throughput_bps,omitempty"`
	UplinkThroughputBps   []float32              `protobuf:"fixed32,1004,rep,packed,name=uplink_throughput_bps,json=uplinkThroughputBps,proto3" json:"uplink_throughput_bps,omitempty"`
	Outages               []*DishOutage          `protobuf:"bytes,1009,rep,name=outages,proto3" json:"outages,omitempty"`
	PowerIn               []float32              `protobuf:"fixed32,1010,rep,packed,name=power_in,json=powerIn,proto3" json:"power_in,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DishGetHistoryResponse) Reset() {
	*x = DishGetHistoryResponse{}
	mi := &file_proto_device_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishGetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishGetHistoryResponse) ProtoMessage() {}

func (x *DishGetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishGetHistoryResponse.ProtoReflect.Descriptor instead.
func (*DishGetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{13}
}

func (x *DishGetHistoryResponse) GetCurrent() uint64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *DishGetHistoryResponse) GetPopPingDropRate() []float32 {
	if x != nil {
		return x.PopPingDropRate
	}
	return nil
}

func (x *DishGetHistoryResponse) GetPopPingLatencyMs() []float32 {
	if x != nil {
		return x.PopPingLatencyMs
	}
	return nil
}

func (x *DishGetHistoryResponse) GetDownlinkThroughputBps() []float32 {
	if x != nil {
		return x.DownlinkThroughputBps
	}
	return nil
}

func (x *DishGetHistoryResponse) GetUplinkThroughputBps() []float32 {
	if x != nil {
		return x.UplinkThroughputBps
	}
	return nil
}

func (x *DishGetHistoryResponse) GetOutages() []*DishOutage {
	if x != nil {
		return x.Outages
	}
	return nil
}

func (x *DishGetHistoryResponse) GetPowerIn() []float32 {
	if x != nil {
		return x.PowerIn
	}
	return nil
}

var File_proto_device_proto protoreflect.FileDescriptor

const file_proto_device_proto_rawDesc = "" +
	"\n" +
	"\x12proto/device.proto\x12\x11SpaceX.API.Device\"\xf9\x01\n" +
	"\aRequest\x12E\n" +
	"\n" +
	"get_status\x18\xec\a \x01(\v2#.SpaceX.API.Device.GetStatusRequestH\x00R\tgetStatus\x12H\n" +
	"\vget_history\x18\xef\a \x01(\v2$.SpaceX.API.Device.GetHistoryRequestH\x00R\n" +
	"getHistory\x12R\n" +
	"\x0fget_device_info\x18\xf0\a \x01(\v2'.SpaceX.API.Device.GetDeviceInfoRequestH\x00R\rgetDeviceInfoB\t\n" +
	"\arequest\"\x98\x02\n" +
	"\bResponse\x12S\n" +
	"\x0fdish_get_status\x18\xd4\x0f \x01(\v2(.SpaceX.API.Device.DishGetStatusResponseH\x00R\rdishGetStatus\x12V\n" +
	"\x10dish_get_history\x18\xd6\x0f \x01(\v2).SpaceX.API.Device.DishGetHistoryResponseH\x00R\x0edishGetHistory\x12S\n" +
	"\x0fget_device_info\x18\xec\a \x01(\v2(.SpaceX.API.Device.GetDeviceInfoResponseH\x00R\rgetDeviceInfoB\n" +
	"\n" +
	"\bresponse\"\x12\n" +
	"\x10GetStatusRequest\"\x13\n" +
	"\x11GetHistoryRequest\"\x16\n" +
	"\x14GetDeviceInfoRequest\"W\n" +
	"\x15GetDeviceInfoResponse\x12>\n" +
	"\vdevice_info\x18\x01 \x01(\v2\x1d.SpaceX.API.Device.DeviceInfoR\n" +
	"deviceInfo\"\xd5\x01\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10hardware_version\x18\x02 \x01(\tR\x0fhardwareVersion\x12)\n" +
	"\x10software_version\x18\x03 \x01(\tR\x0fsoftwareVersion\x12!\n" +
	"\fcountry_code\x18\x04 \x01(\tR\vcountryCode\x12 \n" +
	"\futc_offset_s\x18\x05 \x01(\x05R\n" +
	"utcOffsetS\x12\x1c\n" +
	"\tbootcount\x18\b \x01(\x05R\tbootcount\"\xff\b\n" +
	"\x15DishGetStatusResponse\x12>\n" +
	"\vdevice_info\x18\x01 \x01(\v2\x1d.SpaceX.API.Device.DeviceInfoR\n" +
	"deviceInfo\x12A\n" +
	"\fdevice_state\x18\x02 \x01(\v2\x1e.SpaceX.API.Device.DeviceStateR\vdeviceState\x12,\n" +
	"\x12pop_ping_drop_rate\x18\xeb\a \x01(\x02R\x0fpopPingDropRate\x12U\n" +
	"\x11obstruction_stats\x18\xec\a \x01(\v2'.SpaceX.API.Device.DishObstructionStatsR\x10obstructionStats\x126\n" +
	"\x06alerts\x18\xed\a \x01(\v2\x1d.SpaceX.API.Device.DishAlertsR\x06alerts\x127\n" +
	"\x17downlink_throughput_bps\x18\xef\a \x01(\x02R\x15downlinkThroughputBps\x123\n" +
	"\x15uplink_throughput_bps\x18\xf0\a \x01(\x02R\x13uplinkThroughputBps\x12.\n" +
	"\x13pop_ping_latency_ms\x18\xf1\a \x01(\x02R\x10popPingLatencyMs\x123\n" +
	"\x15boresight_azimuth_deg\x18\xf3\a \x01(\x02R\x13boresightAzimuthDeg\x127\n" +
	"\x17boresight_elevation_deg\x18\xf4\a \x01(\x02R\x15boresightElevationDeg\x126\n" +
	"\x06outage\x18\xf6\a \x01(\v2\x1d.SpaceX.API.Device.DishOutageR\x06outage\x12%\n" +
	"\x0eeth_speed_mbps\x18\xf8\a \x01(\x05R\fethSpeedMbps\x127\n" +
	"\x18is_snr_above_noise_floor\x18\xfa\a \x01(\bR\x14isSnrAboveNoiseFloor\x126\n" +
	"\x17is_snr_persistently_low\x18\xfe\a \x01(\bR\x14isSnrPersistentlyLow\x12K\n" +
	"\x0falignment_stats\x18\x83\b \x01(\v2!.SpaceX.API.Device.AlignmentStatsR\x0ealignmentStats\x12)\n" +
	"\x10is_cell_disabled\x18\x85\b \x01(\bR\x0eisCellDisabled\x12h\n" +
	"\x1edl_bandwidth_restricted_reason\x18\x94\b \x01(\x0e2\".SpaceX.API.Device.RateLimitReasonR\x1bdlBandwidthRestrictedReason\x12h\n" +
	"\x1eul_bandwidth_restricted_reason\x18\x95\b \x01(\x0e2\".SpaceX.API.Device.RateLimitReasonR\x1bulBandwidthRestrictedReason\"(\n" +
	"\vDeviceState\x12\x19\n" +
	"\buptime_s\x18\x01 \x01(\x04R\auptimeS\"\x93\x01\n" +
	"\x14DishObstructionStats\x12/\n" +
	"\x13fraction_obstructed\x18\x01 \x01(\x02R\x12fractionObstructed\x12\x17\n" +
	"\avalid_s\x18\x04 \x01(\x02R\x06validS\x121\n" +
	"\x14currently_obstructed\x18\x05 \x01(\bR\x13currentlyObstructed\"\xb0\a\n" +
	"\n" +
	"DishAlerts\x12!\n" +
	"\fmotors_stuck\x18\x01 \x01(\bR\vmotorsStuck\x12)\n" +
	"\x10thermal_shutdown\x18\x02 \x01(\bR\x0fthermalShutdown\x12)\n" +
	"\x10thermal_throttle\x18\x03 \x01(\bR\x0fthermalThrottle\x12/\n" +
	"\x13unexpected_location\x18\x04 \x01(\bR\x12unexpectedLocation\x123\n" +
	"\x16mast_not_near_vertical\x18\x05 \x01(\bR\x13mastNotNearVertical\x120\n" +
	"\x14slow_ethernet_speeds\x18\x06 \x01(\bR\x12slowEthernetSpeeds\x12\x18\n" +
	"\aroaming\x18\a \x01(\bR\aroaming\x12'\n" +
	"\x0finstall_pending\x18\b \x01(\bR\x0einstallPending\x12\x1d\n" +
	"\n" +
	"is_heating\x18\t \x01(\bR\tisHeating\x12A\n" +
	"\x1dpower_supply_thermal_throttle\x18\n" +
	" \x01(\bR\x1apowerSupplyThermalThrottle\x12+\n" +
	"\x12is_power_save_idle\x18\v \x01(\bR\x0fisPowerSaveIdle\x12&\n" +
	"\x0fdbf_telem_stale\x18\x0e \x01(\bR\rdbfTelemStale\x12*\n" +
	"\x11low_motor_current\x18\x10 \x01(\bR\x0flowMotorCurrent\x12=\n" +
	"\x1blower_signal_than_predicted\x18\x11 \x01(\bR\x18lowerSignalThanPredicted\x127\n" +
	"\x18slow_ethernet_speeds_100\x18\x12 \x01(\bR\x15slowEthernetSpeeds100\x122\n" +
	"\x15obstruction_map_reset\x18\x13 \x01(\bR\x13obstructionMapReset\x12.\n" +
	"\x13dish_water_detected\x18\x14 \x01(\bR\x11dishWaterDetected\x122\n" +
	"\x15router_water_detected\x18\x15 \x01(\bR\x13routerWaterDetected\x121\n" +
	"\x15upsu_router_port_slow\x18\x16 \x01(\bR\x12upsuRouterPortSlow\x12(\n" +
	"\x10no_ethernet_link\x18\x17 \x01(\bR\x0enoEthernetLink\"\x9d\x03\n" +
	"\n" +
	"DishOutage\x129\n" +
	"\x05cause\x18\x01 \x01(\x0e2#.SpaceX.API.Device.DishOutage.CauseR\x05cause\x12,\n" +
	"\x12start_timestamp_ns\x18\x02 \x01(\x03R\x10startTimestampNs\x12\x1f\n" +
	"\vduration_ns\x18\x03 \x01(\x04R\n" +
	"durationNs\x12\x1d\n" +
	"\n" +
	"did_switch\x18\x04 \x01(\bR\tdidSwitch\"\xe5\x01\n" +
	"\x05Cause\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aBOOTING\x10\x01\x12\n" +
	"\n" +
	"\x06STOWED\x10\x02\x12\x14\n" +
	"\x10THERMAL_SHUTDOWN\x10\x03\x12\x0f\n" +
	"\vNO_SCHEDULE\x10\x04\x12\v\n" +
	"\aNO_SATS\x10\x05\x12\x0e\n" +
	"\n" +
	"OBSTRUCTED\x10\x06\x12\x0f\n" +
	"\vNO_DOWNLINK\x10\a\x12\f\n" +
	"\bNO_PINGS\x10\b\x12\x15\n" +
	"\x11ACTUATOR_ACTIVITY\x10\t\x12\x0e\n" +
	"\n" +
	"CABLE_TEST\x10\n" +
	"\x12\f\n" +
	"\bSLEEPING\x10\v\x12\x0e\n" +
	"\n" +
	"SKY_SEARCH\x10\r\x12\x0e\n" +
	"\n" +
	"INHIBIT_RF\x10\x0e\"\xe6\x02\n" +
	"\x0eAlignmentStats\x12$\n" +
	"\x0etilt_angle_deg\x18\x03 \x01(\x02R\ftiltAngleDeg\x122\n" +
	"\x15boresight_azimuth_deg\x18\x04 \x01(\x02R\x13boresightAzimuthDeg\x126\n" +
	"\x17boresight_elevation_deg\x18\x05 \x01(\x02R\x15boresightElevationDeg\x128\n" +
	"\x18attitude_uncertainty_deg\x18\a \x01(\x02R\x16attitudeUncertaintyDeg\x12A\n" +
	"\x1ddesired_boresight_azimuth_deg\x18\b \x01(\x02R\x1adesiredBoresightAzimuthDeg\x12E\n" +
	"\x1fdesired_boresight_elevation_deg\x18\t \x01(\x02R\x1cdesiredBoresightElevationDeg\"\xd4\x02\n" +
	"\x16DishGetHistoryResponse\x12\x18\n" +
	"\acurrent\x18\x01 \x01(\x04R\acurrent\x12,\n" +
	"\x12pop_ping_drop_rate\x18\xe9\a \x03(\x02R\x0fpopPingDropRate\x12.\n" +
	"\x13pop_ping_latency_ms\x18\xea\a \x03(\x02R\x10popPingLatencyMs\x127\n" +
	"\x17downlink_throughput_bps\x18\xeb\a \x03(\x02R\x15downlinkThroughputBps\x123\n" +
	"\x15uplink_throughput_bps\x18\xec\a \x03(\x02R\x13uplinkThroughputBps\x128\n" +
	"\aoutages\x18\xf1\a \x03(\v2\x1d.SpaceX.API.Device.DishOutageR\aoutages\x12\x1a\n" +
	"\bpower_in\x18\xf2\a \x03(\x02R\apowerIn*\xaa\x01\n" +
	"\x0fRateLimitReason\x12\x16\n" +
	"\x12RATE_LIMIT_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fRATE_LIMIT_NONE\x10\x01\x12\x15\n" +
	"\x11RATE_LIMIT_POLICY\x10\x02\x12\x1a\n" +
	"\x16RATE_LIMIT_USER_CUSTOM\x10\x03\x12\x16\n" +
	"\x12RATE_LIMIT_OVERAGE\x10\x05\x12\x1f\n" +
	"\x1bRATE_LIMIT_LOW_SPEED_POLICY\x10\x062K\n" +
	"\x06Device\x12A\n" +
	"\x06Handle\x12\x1a.SpaceX.API.Device.Request\x1a\x1b.SpaceX.API.Device.ResponseB!Z\x1fpp-starlink/proto/device;deviceb\x06proto3"

var (
	file_proto_device_proto_rawDescOnce sync.Once
	file_proto_device_proto_rawDescData []byte
)

func file_proto_device_proto_rawDescGZIP() []byte {
	file_proto_device_proto_rawDescOnce.Do(func() {
		file_proto_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_device_proto_rawDesc), len(file_proto_device_proto_rawDesc)))
	})
	return file_proto_device_proto_rawDescData
}

var file_proto_device_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_device_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_device_proto_goTypes = []any{
	(RateLimitReason)(0),           // 0: SpaceX.API.Device.RateLimitReason
	(DishOutage_Cause)(0),          // 1: SpaceX.API.Device.DishOutage.Cause
	(*Request)(nil),                // 2: SpaceX.API.Device.Request
	(*Response)(nil),               // 3: SpaceX.API.Device.Response
	(*GetStatusRequest)(nil),       // 4: SpaceX.API.Device.GetStatusRequest
	(*GetHistoryRequest)(nil),      // 5: SpaceX.API.Device.GetHistoryRequest
	(*GetDeviceInfoRequest)(nil),   // 6: SpaceX.API.Device.GetDeviceInfoRequest
	(*GetDeviceInfoResponse)(nil),  // 7: SpaceX.API.Device.GetDeviceInfoResponse
	(*DeviceInfo)(nil),             // 8: SpaceX.API.Device.DeviceInfo
	(*DishGetStatusResponse)(nil),  // 9: SpaceX.API.Device.DishGetStatusResponse
	(*DeviceState)(nil),            // 10: SpaceX.API.Device.DeviceState
	(*DishObstructionStats)(nil),   // 11: SpaceX.API.Device.DishObstructionStats
	(*DishAlerts)(nil),             // 12: SpaceX.API.Device.DishAlerts
	(*DishOutage)(nil),             // 13: SpaceX.API.Device.DishOutage
	(*AlignmentStats)(nil),         // 14: SpaceX.API.Device.AlignmentStats
	(*DishGetHistoryResponse)(nil), // 15: SpaceX.API.Device.DishGetHistoryResponse
}
var file_proto_device_proto_depIdxs = []int32{
	4,  // 0: SpaceX.API.Device.Request.get_status:type_name -> SpaceX.API.Device.GetStatusRequest
	5,  // 1: SpaceX.API.Device.Request.get_history:type_name -> SpaceX.API.Device.GetHistoryRequest
	6,  // 2: SpaceX.API.Device.Request.get_device_info:type_name -> SpaceX.API.Device.GetDeviceInfoRequest
	9,  // 3: SpaceX.API.Device.Response.dish_get_status:type_name -> SpaceX.API.Device.DishGetStatusResponse
	15, // 4: SpaceX.API.Device.Response.dish_get_history:type_name -> SpaceX.API.Device.DishGetHistoryResponse
	7,  // 5: SpaceX.API.Device.Response.get_device_info:type_name -> SpaceX.API.Device.GetDeviceInfoResponse
	8,  // 6: SpaceX.API.Device.GetDeviceInfoResponse.device_info:type_name -> SpaceX.API.Device.DeviceInfo
	8,  // 7: SpaceX.API.Device.DishGetStatusResponse.device_info:type_name -> SpaceX.API.Device.DeviceInfo
	10, // 8: SpaceX.API.Device.DishGetStatusResponse.device_state:type_name -> SpaceX.API.Device.DeviceState
	11, // 9: SpaceX.API.Device.DishGetStatusResponse.obstruction_stats:type_name -> SpaceX.API.Device.DishObstructionStats
	12, // 10: SpaceX.API.Device.DishGetStatusResponse.alerts:type_name -> SpaceX.API.Device.DishAlerts
	13, // 11: SpaceX.API.Device.DishGetStatusResponse.outage:type_name -> SpaceX.API.Device.DishOutage
	14, // 12: SpaceX.API.Device.DishGetStatusResponse.alignment_stats:type_name -> SpaceX.API.Device.AlignmentStats
	0,  // 13: SpaceX.API.Device.DishGetStatusResponse.dl_bandwidth_restricted_reason:type_name -> SpaceX.API.Device.RateLimitReason
	0,  // 14: SpaceX.API.Device.DishGetStatusResponse.ul_bandwidth_restricted_reason:type_name -> SpaceX.API.Device.RateLimitReason
	1,  // 15: SpaceX.API.Device.DishOutage.cause:type_name -> SpaceX.API.Device.DishOutage.Cause
	13, // 16: SpaceX.API.Device.DishGetHistoryResponse.outages:type_name -> SpaceX.API.Device.DishOutage
	2,  // 17: SpaceX.API.Device.Device.Handle:input_type -> SpaceX.API.Device.Request
	3,  // 18: SpaceX.API.Device.Device.Handle:output_type -> SpaceX.API.Device.Response
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_device_proto_init() }
func file_proto_device_proto_init() {
	if File_proto_device_proto != nil {
		return
	}
	file_proto_device_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_GetStatus)(nil),
		(*Request_GetHistory)(nil),
		(*Request_GetDeviceInfo)(nil),
	}
	file_proto_device_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_DishGetStatus)(nil),
		(*Response_DishGetHistory)(nil),
		(*Response_GetDeviceInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_device_proto_rawDesc), len(file_proto_device_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_device_proto_goTypes,
		DependencyIndexes: file_proto_device_proto_depIdxs,
		EnumInfos:         file_proto_device_proto_enumTypes,
		MessageInfos:      file_proto_device_proto_msgTypes,
	}.Build()
	File_proto_device_proto = out.File
	file_proto_device_proto_goTypes = nil
	file_proto_device_proto_depIdxs = nil
}
