#!/usr/bin/env python3
"""Bootstrap a virtual environment with the correct Python interpreter.

Generated by athena upgrade into .athena/bootstrap.py.  Called by both
Makefile.inc targets and the athena-ci.yml reusable workflow.

Usage:
    python .athena/bootstrap.py <venv-dir>        # create venv (layers 0-2)
    python .athena/bootstrap.py --print-python    # print chosen interpreter

This script is a pure INFRASTRUCTURE primitive.  Its ONLY job is:

    1. SELECT the best interpreter satisfying ``requires-python``
    2. CREATE a venv with that interpreter (via subprocess, never stdlib venv)
    3. SEED pip to the declared floor version from athena.toml

It does NOT install athena, lockfiles, or anything application-level.
The caller (Makefile.inc or equivalent) handles layer 3+ (install athena)
and layer 4 (install lockfiles) however it wants.

The Makefile seeds this script with a bare ``python3``.  The script then
intelligently selects the best interpreter (lowest stable system interpreter,
preferring real over venv, rejecting pre-releases) by *executing* each
candidate -- so a name that lies about its version cannot fool it -- and
re-execs itself under that validated ABSOLUTE interpreter.

All version parsing is plain-text regex (no ``tomllib``) so the script runs
far enough on a too-old interpreter to fail with a clear, actionable message.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

_REQUIRES_PYTHON_RE = re.compile(
    r"""requires-python\s*=\s*["']([^"']+)["']"""
)
_FLOOR_RE = re.compile(r"(\d+)\.(\d+)")
_CEILING_RE = re.compile(r"<\s*(\d+)\.(\d+)")
_PY_NAME_RE = re.compile(r"^python3(\.\d+)?$")
_REEXEC_GUARD = "_ATHENA_BOOTSTRAP_REEXEC"
_PIP_FLOOR_RE = re.compile(
    r'^\[pip\]\s*\n(?:[^[]*?\n)*?floor\s*=\s*"([^"]+)"', re.MULTILINE
)
_PROBE = (
    "import sys;"
    "v=sys.version_info;"
    "print('%d.%d.%d %d %s' % (v[0], v[1], v[2],"
    " 1 if sys.prefix != sys.base_prefix else 0, v.releaselevel))"
)


# ---------------------------------------------------------------------------
# Interpreter selection (layer 0)
# ---------------------------------------------------------------------------

def _python_bounds() -> tuple[tuple[int, int] | None, tuple[int, int] | None]:
    """Parse requires-python (floor, ceiling) from pyproject.toml as text."""
    try:
        text = Path("pyproject.toml").read_text(encoding="utf-8")
    except OSError:
        return (None, None)
    spec = _REQUIRES_PYTHON_RE.search(text)
    if spec is None:
        return (None, None)
    raw = spec.group(1)
    floor_m = _FLOOR_RE.search(raw)
    floor = (int(floor_m.group(1)), int(floor_m.group(2))) if floor_m else None
    ceil_m = _CEILING_RE.search(raw)
    ceil = (int(ceil_m.group(1)), int(ceil_m.group(2))) if ceil_m else None
    return (floor, ceil)


def _require_minimum_python() -> None:
    """Fail loudly if the running interpreter is below the project floor."""
    floor = _python_bounds()[0]
    if floor is None:
        return
    actual = sys.version_info[:2]  # capture-exempt: pre-athena bootstrap
    if actual >= floor:
        return
    floor_str = f"{floor[0]}.{floor[1]}"
    actual_str = f"{actual[0]}.{actual[1]}.{sys.version_info[2]}"  # capture-exempt: pre-athena bootstrap
    sys.stderr.write(
        f"ERROR: athena bootstrap requires Python >={floor_str}, but the "
        f"interpreter actually running this script is {actual_str}.\n"
        f"  interpreter: {sys.executable}\n"  # capture-exempt: pre-athena bootstrap
        f"Install a real Python >={floor_str} and make sure it is the one "
        f"invoked (check ATHENA_PYTHON and your PATH).\n"
    )
    raise SystemExit(1)


def _candidate_commands() -> list[str]:
    """Return every python3 / python3.NN command name found on PATH."""
    names: set[str] = {"python3"}
    for directory in os.environ.get("PATH", "").split(os.pathsep):
        if not directory:
            continue
        try:
            entries = [p.name for p in Path(directory).iterdir()]
        except OSError:
            continue
        for entry in entries:
            if _PY_NAME_RE.match(entry):
                names.add(entry)
    return sorted(names)


def _probe(cmd: str) -> tuple[str, tuple[int, int, int], bool, str] | None:
    """Execute one candidate interpreter and read its real identity.

    Returns None if the command is not found or crashes.  Raises ValueError
    if the interpreter runs successfully but produces unparseable output --
    that indicates a broken environment (e.g. a .pth file injecting output
    before the probe snippet) and must not be silently skipped.
    """
    exe = shutil.which(cmd)
    if exe is None:
        return None
    # Resolve to real path at point of discovery.  shutil.which returns
    # an absolute path but does NOT resolve symlinks.  An activated venv
    # puts venv/bin/ on PATH, so ``which python3`` returns e.g.
    # ``venv/bin/python3`` -- a symlink that goes dead if the venv is
    # renamed aside during recreation.  Resolving here guarantees every
    # downstream consumer holds a path to the real binary.
    exe = str(Path(exe).resolve())
    try:
        proc = subprocess.run(
            [exe, "-c", _PROBE],
            capture_output=True,
            text=True,
            timeout=15,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if proc.returncode != 0:
        return None
    parts = proc.stdout.split()
    if len(parts) != 3:
        msg = (
            f"Interpreter {exe} ran successfully but produced unparseable "
            f"output (expected 3 tokens, got {len(parts)}): "
            f"{proc.stdout.strip()!r}"
        )
        raise ValueError(msg)
    ver_str, is_venv_str, releaselevel = parts
    try:
        major, minor, micro = (int(x) for x in ver_str.split("."))
    except ValueError:
        msg = (
            f"Interpreter {exe} reported non-numeric version: {ver_str!r}"
        )
        raise ValueError(msg) from None
    return (exe, (major, minor, micro), is_venv_str == "1", releaselevel)


def _select_interpreter() -> tuple[str | None, list[tuple[str, str]]]:
    """Pick the best interpreter satisfying requires-python.

    Among interpreters that satisfy [floor, ceiling) and are stable (not
    pre-releases), prefer the LOWEST version and prefer a real system
    interpreter over one inside a virtual environment.
    """
    floor, ceil = _python_bounds()
    best_sys: tuple[tuple[int, int, int], str] | None = None
    best_venv: tuple[tuple[int, int, int], str] | None = None
    found: list[tuple[str, str]] = []
    for cmd in _candidate_commands():
        probed = _probe(cmd)
        if probed is None:
            continue
        exe, version, is_venv, releaselevel = probed
        found.append((exe, f"{version[0]}.{version[1]}.{version[2]}"))
        minor_pair = version[:2]
        if floor is not None and minor_pair < floor:
            continue
        if ceil is not None and minor_pair >= ceil:
            continue
        if releaselevel != "final":
            continue
        if is_venv:
            if best_venv is None or version < best_venv[0]:
                best_venv = (version, exe)
        elif best_sys is None or version < best_sys[0]:
            best_sys = (version, exe)
    chosen = best_sys or best_venv
    return (chosen[1] if chosen else None, found)


def _resolve_interpreter_or_die() -> str:
    """Return the selected interpreter path, or exit 1 with diagnostics."""
    path, found = _select_interpreter()
    if path is not None:
        return path
    floor, ceil = _python_bounds()
    floor_str = f">={floor[0]}.{floor[1]}" if floor else "(any)"
    ceil_str = f",<{ceil[0]}.{ceil[1]}" if ceil else ""
    sys.stderr.write(
        f"ERROR: no suitable Python interpreter found on PATH for "
        f"requires-python {floor_str}{ceil_str}.\n"
    )
    if found:
        sys.stderr.write("Interpreters probed (rejected):\n")
        for exe, version in found:
            sys.stderr.write(f"  {version}\t{exe}\n")
    sys.stderr.write(
        "Install a stable Python in range and ensure it is on PATH.\n"
    )
    raise SystemExit(1)


# ---------------------------------------------------------------------------
# Venv creation (layer 1)
# ---------------------------------------------------------------------------

def _create_venv(python: str, venv_dir: Path) -> None:
    """Create the venv via subprocess, moving any existing one aside first.

    Uses ``python -m venv`` as a SUBPROCESS of the selected interpreter --
    never stdlib ``venv.create()`` from the running process.  The running
    process may be a different Python version (e.g. the bare python3 seed).

    Writing a fresh interpreter over the currently-running one raises
    ETXTBSY.  Renaming the directory aside is safe -- the open interpreter
    keeps its inode.  ``python`` is always a resolved real path (guaranteed
    by ``_probe``), so it survives the rename even if it was originally a
    symlink inside ``venv_dir``.
    """
    backup_dir = venv_dir.with_suffix(".bak")
    had_backup = False
    if venv_dir.exists():
        if backup_dir.exists():
            shutil.rmtree(backup_dir)
        venv_dir.rename(backup_dir)
        had_backup = True

    try:
        subprocess.run(
            [python, "-m", "venv", str(venv_dir)],
            check=True,
        )
    except BaseException:
        if had_backup:
            if venv_dir.exists():
                shutil.rmtree(venv_dir)
            backup_dir.rename(venv_dir)
        raise

    if had_backup:
        shutil.rmtree(backup_dir)


def _assert_venv_version(python: str, venv_dir: Path) -> None:
    """Assert the venv's interpreter version matches the source interpreter.

    This is the single structural defense against the sys._base_executable
    bug: CPython's venv module uses _base_executable internally, which inside
    a copied-binary venv may point to the system python3 (a different version).
    By always creating venvs via subprocess with the VALIDATED interpreter,
    and then asserting the result here, any regression is caught immediately
    with a clear diagnostic rather than surfacing later as a hash mismatch.
    """
    venv_python = str(venv_dir / "bin" / "python")
    source_proc = subprocess.run(
        [python, "-c", "import sys; print(f'{sys.version_info[0]}.{sys.version_info[1]}')"],
        capture_output=True, text=True, check=True,
    )
    venv_proc = subprocess.run(
        [venv_python, "-c", "import sys; print(f'{sys.version_info[0]}.{sys.version_info[1]}')"],
        capture_output=True, text=True, check=True,
    )
    source_ver = source_proc.stdout.strip()
    venv_ver = venv_proc.stdout.strip()
    if source_ver != venv_ver:
        msg = (
            f"venv interpreter version mismatch: "
            f"source {python} reports {source_ver}, "
            f"venv {venv_python} reports {venv_ver}. "
            f"This indicates a sys._base_executable leak in CPython's venv "
            f"module -- the venv was NOT created by the intended interpreter. "
            f"Fix: use a versioned binary (e.g. python3.12) not a copied "
            f"binary from another venv."
        )
        raise RuntimeError(msg)


# ---------------------------------------------------------------------------
# Pip seeding (layer 2)
# ---------------------------------------------------------------------------

def _pip_floor() -> str | None:
    """Read [pip].floor from athena.toml as text (no tomllib)."""
    try:
        text = Path("athena.toml").read_text(encoding="utf-8")
    except OSError:
        return None
    m = _PIP_FLOOR_RE.search(text)
    return m.group(1) if m else None


def _seed_pip(venv_dir: Path) -> None:
    """Upgrade pip to at least the declared floor version."""
    pip = str(venv_dir / "bin" / "pip")
    floor = _pip_floor()
    pip_spec = f"pip>={floor}" if floor else "pip"
    subprocess.run(
        [pip, "install", "--disable-pip-version-check", "--upgrade", "--quiet",
         pip_spec, "setuptools"],
        check=True,
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:  # noqa: D103
    flags = {a for a in sys.argv[1:] if a.startswith("--")}
    positional = [a for a in sys.argv[1:] if not a.startswith("--")]

    # --print-python: resolve and print the chosen interpreter, then exit.
    if "--print-python" in flags:
        print(_resolve_interpreter_or_die())
        return 0

    # Self-select the best interpreter and re-run under it (once).
    if not os.environ.get(_REEXEC_GUARD):
        chosen = _resolve_interpreter_or_die()
        if Path(chosen).resolve() != Path(sys.executable).resolve():  # capture-exempt: pre-athena bootstrap
            env = dict(os.environ)
            env[_REEXEC_GUARD] = "1"
            proc = subprocess.run(
                [chosen, str(Path(__file__).resolve()), *sys.argv[1:]],
                env=env,
                check=False,
            )
            return proc.returncode
        os.environ[_REEXEC_GUARD] = "1"

    _require_minimum_python()

    if len(positional) < 1:
        print("Usage: python .athena/bootstrap.py <venv-dir>", file=sys.stderr)
        return 1

    venv_dir = Path(positional[0])

    # ATHENA_TMPDIR for pip temp files
    tmpdir = os.environ.get("ATHENA_TMPDIR", "")
    if tmpdir:
        os.environ["TMPDIR"] = tmpdir
        Path(tmpdir).mkdir(parents=True, exist_ok=True)

    # sys.executable is the post-reexec interpreter.  After reexec,
    # sys.executable equals the chosen interpreter from _probe, which
    # is already resolved to a real path.  Resolve again as belt-and-
    # suspenders defense (e.g. if someone bypasses reexec).
    python = str(Path(sys.executable).resolve())  # capture-exempt: post-reexec, real path
    print(f"Creating venv in {venv_dir} using {python} ...")
    _create_venv(python, venv_dir)
    try:
        _assert_venv_version(python, venv_dir)
    except RuntimeError as e:
        print(f"FATAL: {e}", file=sys.stderr)
        return 1
    _seed_pip(venv_dir)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
