#!/usr/bin/env python3
"""Download and install the athena wheel into an existing venv.

Generated by athena upgrade into .athena/fetch_wheel.py.  Called by
Makefile.inc after bootstrap.py has created the venv.

Usage:
    python .athena/fetch_wheel.py <venv-dir>            # download + install
    python .athena/fetch_wheel.py <venv-dir> <path>     # install from local wheel

Reads the athena version pin from pyproject.toml (single source of truth).
Downloads the wheel from GitHub Releases to a cache directory.

Auth (checked in order):
    - GITHUB_TOKEN / GH_TOKEN env var (CI, GitHub Actions)
    - gh auth token (local dev with gh CLI)
"""

from __future__ import annotations

import json
import os
import re
import shutil
import ssl
import subprocess
import sys
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen

_ATHENA_PIN_RE = re.compile(
    r"metrostar-athena\s*@\s*git\+https://github\.com/MetroStar/athena\.git@v([\d.]+)"
)


def _ssl_context() -> ssl.SSLContext:
    """SSL context honoring corporate CA-bundle env vars."""
    ctx = ssl.create_default_context()
    bundle = (
        os.environ.get("SSL_CERT_FILE")
        or os.environ.get("REQUESTS_CA_BUNDLE")
        or os.environ.get("CURL_CA_BUNDLE")
    )
    if bundle and Path(bundle).is_file():
        ctx.load_verify_locations(cafile=bundle)
    return ctx


def _read_athena_version() -> str:
    """Extract the metrostar-athena version pin from pyproject.toml."""
    try:
        text = Path("pyproject.toml").read_text(encoding="utf-8")
    except OSError:
        msg = "pyproject.toml not found"
        raise SystemExit(msg) from None
    m = _ATHENA_PIN_RE.search(text)
    if m:
        return m.group(1)
    msg = "metrostar-athena pin not found in pyproject.toml"
    raise SystemExit(msg)


def _get_token() -> str:
    """Resolve GitHub auth token from environment or gh CLI."""
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN") or ""
    if token:
        return token
    if shutil.which("gh"):
        result = subprocess.run(
            ["gh", "auth", "token"],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    return ""


def _download_with_gh(version: str, cache: Path) -> bool:
    """Try downloading via gh CLI."""
    if not shutil.which("gh"):
        return False
    result = subprocess.run(
        [
            "gh", "release", "download", f"v{version}",
            "--repo", "MetroStar/athena",
            "-p", "*.whl",
            "-D", str(cache),
            "--clobber",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0


def _download_with_api(version: str, wheel: Path, token: str) -> bool:
    """Download wheel via GitHub Releases API with token auth."""
    if not token:
        return False
    release_url = (
        f"https://api.github.com/repos/MetroStar/athena"
        f"/releases/tags/v{version}"
    )
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }
    try:
        req = Request(release_url, headers=headers)
        with urlopen(req, context=_ssl_context()) as resp:
            data = json.loads(resp.read())
    except (HTTPError, OSError) as exc:
        print(f"  WARNING: release lookup failed: {exc}", file=sys.stderr)
        return False

    asset_url = ""
    for asset in data.get("assets", []):
        if asset["name"].endswith(".whl"):
            asset_url = asset["url"]
            break

    if not asset_url:
        print("  WARNING: no .whl asset found in release", file=sys.stderr)
        return False

    dl_headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/octet-stream",
    }
    try:
        req = Request(asset_url, headers=dl_headers)
        with urlopen(req, context=_ssl_context()) as resp:
            wheel.write_bytes(resp.read())
    except (HTTPError, OSError) as exc:
        print(f"  WARNING: wheel download failed: {exc}", file=sys.stderr)
        return False
    return True


def _download_wheel(version: str, wheel: Path, cache: Path) -> None:
    """Download the athena wheel using available auth methods."""
    print(f"Downloading athena v{version} wheel...")
    token = _get_token()

    if not token and _download_with_gh(version, cache):
        return
    if token and _download_with_api(version, wheel, token):
        return
    if _download_with_gh(version, cache):
        return

    print(
        "ERROR: cannot download wheel (no gh CLI and no GITHUB_TOKEN)",
        file=sys.stderr,
    )
    raise SystemExit(1)


def _pip(venv_dir: Path, *args: str) -> None:
    """Run pip in the target venv."""
    cmd = [str(venv_dir / "bin" / "pip"), *args]
    subprocess.run(cmd, check=True)


def main() -> int:
    """Download and install the athena wheel into an existing venv."""
    positional = [a for a in sys.argv[1:] if not a.startswith("--")]

    if len(positional) < 1:
        print(
            "Usage: python .athena/fetch_wheel.py <venv-dir> [wheel-path]",
            file=sys.stderr,
        )
        return 1

    venv_dir = Path(positional[0])
    source = positional[1] if len(positional) > 1 else ""

    version = _read_athena_version()

    # Wheel cache directory
    env_cache = os.environ.get("ATHENA_CACHE", "")
    cache = Path(env_cache) if env_cache else (
        Path.home() / ".cache" / "athena" / "wheels"
    )
    cache.mkdir(parents=True, exist_ok=True)
    wheel = cache / f"metrostar_athena-{version}-py3-none-any.whl"

    if source:
        source_path = Path(source)
        if not source_path.is_file():
            print(f"ERROR: source file not found: {source}", file=sys.stderr)
            return 1
        shutil.copy2(source_path, wheel)
    elif not wheel.is_file():
        _download_wheel(version, wheel, cache)

    print(f"Installing athena v{version}...")
    _pip(venv_dir, "install", "--no-deps", "--find-links", str(cache),
         str(wheel))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
